/*
 * Exhale Project Original (2026)
 * ozyern (github.com/ozyern)
 * Licensed Under GPL-3.0 | see git history for contributors
 */

package com.ozyern.exhale.ui.screens.settings

import com.ozyern.exhale.R

/** A title in the index: a string resource, so it follows the app's language, or plain text. */
sealed interface IndexText {
    data class Res(val id: Int) : IndexText
    data class Plain(val text: String) : IndexText
}

/** One setting, where it lives, and the section it sits under there. */
data class SettingsIndexEntry(
    val route: String,
    val page: String,
    val section: IndexText?,
    val title: IndexText,
    /** Other words people use for this setting, searched along with its title. */
    val keywords: List<String> = emptyList(),
)

/**
 * Every individual setting on every settings page, so search finds the setting and not just the
 * page it might be on. Generated from the pages' own rows; keep it in step when adding one.
 */
val SettingsIndex: List<SettingsIndexEntry> = listOf(
    SettingsIndexEntry("settings/appearance", "Appearance", IndexText.Res(R.string.theme), IndexText.Res(R.string.sabrina_theme)),
    SettingsIndexEntry("settings/appearance", "Appearance", IndexText.Res(R.string.theme), IndexText.Res(R.string.enable_dynamic_theme)),
    SettingsIndexEntry("settings/appearance", "Appearance", IndexText.Res(R.string.theme), IndexText.Res(R.string.player_fullscreen)),
    SettingsIndexEntry("settings/appearance", "Appearance", IndexText.Res(R.string.theme), IndexText.Res(R.string.random_theme_on_startup)),
    SettingsIndexEntry("settings/appearance", "Appearance", IndexText.Res(R.string.theme), IndexText.Res(R.string.color_palette)),
    SettingsIndexEntry("settings/appearance", "Appearance", IndexText.Res(R.string.theme), IndexText.Res(R.string.dark_theme)),
    SettingsIndexEntry("settings/appearance", "Appearance", IndexText.Res(R.string.theme), IndexText.Plain("AMOLED black"), listOf("amoled", "oled", "pure black", "black", "true black", "dark", "night", "battery")),
    SettingsIndexEntry("settings/appearance", "Appearance", IndexText.Res(R.string.theme), IndexText.Res(R.string.use_system_font)),
    SettingsIndexEntry("settings/appearance", "Appearance", IndexText.Res(R.string.display), IndexText.Res(R.string.ui_scale)),
    SettingsIndexEntry("settings/appearance", "Appearance", IndexText.Res(R.string.display), IndexText.Res(R.string.app_icon)),
    SettingsIndexEntry("settings/appearance", "Appearance", IndexText.Res(R.string.player), IndexText.Res(R.string.customized_background)),
    SettingsIndexEntry("settings/appearance", "Appearance", IndexText.Res(R.string.player), IndexText.Plain("Music-reactive player")),
    SettingsIndexEntry("settings/appearance", "Appearance", IndexText.Res(R.string.player), IndexText.Plain("Animated covers")),
    SettingsIndexEntry("settings/appearance", "Appearance", IndexText.Plain("Artists"), IndexText.Plain("Artist name style")),
    SettingsIndexEntry("settings/appearance", "Appearance", IndexText.Res(R.string.player), IndexText.Res(R.string.hide_player_thumbnail)),
    SettingsIndexEntry("settings/appearance", "Appearance", IndexText.Res(R.string.player), IndexText.Plain("Canvas source")),
    SettingsIndexEntry("settings/appearance", "Appearance", IndexText.Res(R.string.player), IndexText.Res(R.string.crop_thumbnail_to_square)),
    SettingsIndexEntry("settings/appearance", "Appearance", IndexText.Res(R.string.player), IndexText.Res(R.string.player_buttons_style)),
    SettingsIndexEntry("settings/appearance", "Appearance", IndexText.Res(R.string.player), IndexText.Res(R.string.enable_swipe_thumbnail)),
    SettingsIndexEntry("settings/appearance", "Appearance", IndexText.Res(R.string.player), IndexText.Res(R.string.swipe_sensitivity)),
    SettingsIndexEntry("settings/appearance", "Appearance", IndexText.Plain("Dock"), IndexText.Plain("Dock style"), listOf("dock", "navigation", "nav bar", "navbar", "bottom bar", "tab bar", "tabs", "menu bar", "jelly", "liquid glass", "pill", "style", "look")),
    SettingsIndexEntry("settings/appearance", "Appearance", IndexText.Plain("Dock"), IndexText.Plain("Tab labels"), listOf("dock", "navigation", "nav bar", "navbar", "bottom bar", "tab bar", "tabs", "menu bar", "jelly", "names", "text", "titles", "icons only")),
    SettingsIndexEntry("settings/appearance", "Appearance", IndexText.Plain("Dock"), IndexText.Plain("Compact dock"), listOf("dock", "navigation", "nav bar", "navbar", "bottom bar", "tab bar", "tabs", "menu bar", "jelly", "small", "smaller", "slim", "short", "size")),
    SettingsIndexEntry("settings/appearance", "Appearance", IndexText.Plain("Dock"), IndexText.Plain("Touch glow"), listOf("dock", "navigation", "nav bar", "navbar", "bottom bar", "tab bar", "tabs", "menu bar", "jelly", "glow", "light", "highlight", "drag")),
    SettingsIndexEntry("settings/appearance", "Appearance", IndexText.Plain("Settings page"), IndexText.Plain("Search bar"), listOf("settings search", "search bar", "search position", "top", "bottom", "move search", "search at top", "settings page", "layout", "customise", "customize")),
    SettingsIndexEntry("settings/appearance", "Appearance", IndexText.Res(R.string.misc), IndexText.Res(R.string.default_open_tab)),
    SettingsIndexEntry("settings/appearance", "Appearance", IndexText.Res(R.string.misc), IndexText.Res(R.string.default_lib_chips)),
    SettingsIndexEntry("settings/appearance", "Appearance", IndexText.Res(R.string.misc), IndexText.Plain("Always On Display")),
    SettingsIndexEntry("settings/appearance", "Appearance", IndexText.Res(R.string.misc), IndexText.Plain("Widget Settings")),
    SettingsIndexEntry("settings/appearance", "Appearance", IndexText.Res(R.string.misc), IndexText.Res(R.string.show_home_category_chips)),
    SettingsIndexEntry("settings/appearance", "Appearance", IndexText.Res(R.string.misc), IndexText.Res(R.string.show_tags_in_library)),
    SettingsIndexEntry("settings/appearance", "Appearance", IndexText.Res(R.string.misc), IndexText.Res(R.string.swipe_song_to_add)),
    SettingsIndexEntry("settings/appearance", "Appearance", IndexText.Res(R.string.misc), IndexText.Res(R.string.slim_navbar)),
    SettingsIndexEntry("settings/appearance", "Appearance", IndexText.Res(R.string.misc), IndexText.Res(R.string.grid_cell_size)),
    SettingsIndexEntry("settings/appearance", "Appearance", IndexText.Res(R.string.auto_playlists), IndexText.Res(R.string.show_liked_playlist)),
    SettingsIndexEntry("settings/appearance", "Appearance", IndexText.Res(R.string.auto_playlists), IndexText.Res(R.string.show_downloaded_playlist)),
    SettingsIndexEntry("settings/appearance", "Appearance", IndexText.Res(R.string.auto_playlists), IndexText.Res(R.string.show_top_playlist)),
    SettingsIndexEntry("settings/appearance", "Appearance", IndexText.Res(R.string.auto_playlists), IndexText.Res(R.string.show_cached_playlist)),
    SettingsIndexEntry("settings/appearance", "Appearance", IndexText.Res(R.string.auto_playlists), IndexText.Res(R.string.appearance)),
    SettingsIndexEntry("settings/player", "Player & audio", IndexText.Plain("None"), IndexText.Res(R.string.player_stream_client)),
    SettingsIndexEntry("settings/player", "Player & audio", IndexText.Plain("Streaming"), IndexText.Res(R.string.audio_quality)),
    SettingsIndexEntry("settings/player", "Player & audio", IndexText.Plain("Streaming"), IndexText.Res(R.string.audio_codec)),
    SettingsIndexEntry("settings/player", "Player & audio", IndexText.Plain("Streaming"), IndexText.Plain("Prefer music-only version")),
    SettingsIndexEntry("settings/player", "Player & audio", IndexText.Plain("Streaming"), IndexText.Plain("Prefer lossless files")),
    SettingsIndexEntry("settings/player", "Player & audio", IndexText.Plain("Streaming"), IndexText.Res(R.string.network_metered_title)),
    SettingsIndexEntry("settings/player", "Player & audio", IndexText.Plain("Output"), IndexText.Plain("Prefer USB DAC")),
    SettingsIndexEntry("settings/player", "Player & audio", IndexText.Plain("Sound"), IndexText.Plain("Equalizer")),
    SettingsIndexEntry("settings/player", "Player & audio", IndexText.Plain("Sound"), IndexText.Res(R.string.spatial_audio)),
    SettingsIndexEntry("settings/player", "Player & audio", IndexText.Plain("Sound"), IndexText.Res(R.string.audio_normalization)),
    SettingsIndexEntry("settings/player", "Player & audio", IndexText.Plain("Sound"), IndexText.Plain("Automix")),
    SettingsIndexEntry("settings/player", "Player & audio", IndexText.Plain("Sound"), IndexText.Res(R.string.skip_silence)),
    SettingsIndexEntry("settings/player", "Player & audio", IndexText.Plain("Sound"), IndexText.Res(R.string.audio_offload)),
    SettingsIndexEntry("settings/player", "Player & audio", IndexText.Plain("Playback"), IndexText.Res(R.string.history_duration)),
    SettingsIndexEntry("settings/player", "Player & audio", IndexText.Plain("Playback"), IndexText.Res(R.string.seek_seconds_addup)),
    SettingsIndexEntry("settings/player", "Player & audio", IndexText.Plain("Devices"), IndexText.Res(R.string.pause_on_device_mute)),
    SettingsIndexEntry("settings/player", "Player & audio", IndexText.Plain("Devices"), IndexText.Res(R.string.auto_start_on_bluetooth)),
    SettingsIndexEntry("settings/player", "Player & audio", IndexText.Res(R.string.queue), IndexText.Res(R.string.persistent_queue)),
    SettingsIndexEntry("settings/player", "Player & audio", IndexText.Res(R.string.queue), IndexText.Res(R.string.permanent_shuffle)),
    SettingsIndexEntry("settings/player", "Player & audio", IndexText.Res(R.string.queue), IndexText.Res(R.string.auto_download_on_like)),
    SettingsIndexEntry("settings/player", "Player & audio", IndexText.Res(R.string.queue), IndexText.Res(R.string.auto_skip_next_on_error)),
    SettingsIndexEntry("settings/player", "Player & audio", IndexText.Res(R.string.misc), IndexText.Res(R.string.stop_music_on_task_clear)),
    SettingsIndexEntry("settings/player", "Player & audio", IndexText.Res(R.string.misc), IndexText.Res(R.string.wakelock)),
    SettingsIndexEntry("settings/player", "Player & audio", IndexText.Res(R.string.misc), IndexText.Res(R.string.artist_separators)),
    SettingsIndexEntry("settings/player", "Player & audio", IndexText.Res(R.string.misc), IndexText.Res(R.string.manage_playlist_tags)),
    SettingsIndexEntry("settings/player", "Player & audio", IndexText.Res(R.string.misc), IndexText.Res(R.string.external_downloader)),
    SettingsIndexEntry("settings/player", "Player & audio", IndexText.Res(R.string.misc), IndexText.Res(R.string.external_downloader_package)),
    SettingsIndexEntry("settings/player", "Player & audio", IndexText.Res(R.string.misc), IndexText.Res(R.string.player_and_audio)),
    SettingsIndexEntry("settings/content", "Content", IndexText.Res(R.string.general), IndexText.Plain("Song preferences")),
    SettingsIndexEntry("settings/content", "Content", IndexText.Res(R.string.general), IndexText.Plain("Set your audio languages & favorite artists")),
    SettingsIndexEntry("settings/content", "Content", IndexText.Res(R.string.general), IndexText.Res(R.string.content_language)),
    SettingsIndexEntry("settings/content", "Content", IndexText.Res(R.string.general), IndexText.Res(R.string.content_country)),
    SettingsIndexEntry("settings/content", "Content", IndexText.Res(R.string.general), IndexText.Res(R.string.hide_explicit)),
    SettingsIndexEntry("settings/content", "Content", IndexText.Res(R.string.general), IndexText.Res(R.string.hide_video)),
    SettingsIndexEntry("settings/content", "Content", IndexText.Res(R.string.app_language), IndexText.Res(R.string.app_language)),
    SettingsIndexEntry("settings/content", "Content", IndexText.Res(R.string.proxy), IndexText.Res(R.string.enable_proxy)),
    SettingsIndexEntry("settings/content", "Content", IndexText.Res(R.string.proxy), IndexText.Res(R.string.proxy_type)),
    SettingsIndexEntry("settings/content", "Content", IndexText.Res(R.string.proxy), IndexText.Res(R.string.proxy_url)),
    SettingsIndexEntry("settings/content", "Content", IndexText.Res(R.string.proxy), IndexText.Res(R.string.stream_bypass_proxy)),
    SettingsIndexEntry("settings/content", "Content", IndexText.Res(R.string.lyrics), IndexText.Plain("Lyrics sources")),
    SettingsIndexEntry("settings/content", "Content", IndexText.Res(R.string.lyrics), IndexText.Res(R.string.lyrics_romanize_japanese)),
    SettingsIndexEntry("settings/content", "Content", IndexText.Res(R.string.lyrics), IndexText.Res(R.string.lyrics_romanize_korean)),
    SettingsIndexEntry("settings/content", "Content", IndexText.Res(R.string.lyrics), IndexText.Res(R.string.preload_queue_lyrics)),
    SettingsIndexEntry("settings/content", "Content", IndexText.Res(R.string.lyrics), IndexText.Res(R.string.lock_screen_lyrics)),
    SettingsIndexEntry("settings/content", "Content", IndexText.Res(R.string.lyrics), IndexText.Plain("Lyrics screen on the lock screen")),
    SettingsIndexEntry("settings/content", "Content", IndexText.Res(R.string.lyrics), IndexText.Res(R.string.lyrics_on_media_card)),
    SettingsIndexEntry("settings/content", "Content", IndexText.Res(R.string.lyrics), IndexText.Res(R.string.queue_lyrics_preload_count)),
    SettingsIndexEntry("settings/content", "Content", IndexText.Res(R.string.misc), IndexText.Res(R.string.top_length)),
    SettingsIndexEntry("settings/content", "Content", IndexText.Res(R.string.misc), IndexText.Res(R.string.set_quick_picks)),
    SettingsIndexEntry("settings/content", "Content", IndexText.Res(R.string.misc), IndexText.Res(R.string.content)),
    SettingsIndexEntry("settings/storage", "Storage", IndexText.Plain("None"), IndexText.Res(R.string.smart_trimmer)),
    SettingsIndexEntry("settings/storage", "Storage", IndexText.Plain("None"), IndexText.Res(R.string.clear_all_downloads)),
    SettingsIndexEntry("settings/storage", "Storage", IndexText.Plain("None"), IndexText.Res(R.string.max_cache_size)),
    SettingsIndexEntry("settings/storage", "Storage", IndexText.Plain("None"), IndexText.Res(R.string.clear_song_cache)),
    SettingsIndexEntry("settings/storage", "Storage", IndexText.Plain("None"), IndexText.Res(R.string.clear_image_cache)),
    SettingsIndexEntry("settings/storage", "Storage", IndexText.Plain("None"), IndexText.Res(R.string.clear_canvas_cache)),
    SettingsIndexEntry("settings/storage", "Storage", IndexText.Plain("None"), IndexText.Res(R.string.storage)),
    SettingsIndexEntry("settings/privacy", "Privacy", IndexText.Res(R.string.listen_history), IndexText.Res(R.string.pause_listen_history)),
    SettingsIndexEntry("settings/privacy", "Privacy", IndexText.Res(R.string.listen_history), IndexText.Res(R.string.clear_listen_history)),
    SettingsIndexEntry("settings/privacy", "Privacy", IndexText.Res(R.string.search_history), IndexText.Res(R.string.pause_search_history)),
    SettingsIndexEntry("settings/privacy", "Privacy", IndexText.Res(R.string.search_history), IndexText.Res(R.string.clear_search_history)),
    SettingsIndexEntry("settings/privacy", "Privacy", IndexText.Res(R.string.misc), IndexText.Res(R.string.disable_screenshot)),
    SettingsIndexEntry("settings/privacy", "Privacy", IndexText.Res(R.string.misc), IndexText.Res(R.string.privacy)),
    SettingsIndexEntry("settings/backup_restore", "Backup & restore", IndexText.Plain("None"), IndexText.Res(R.string.backup_restore)),
    SettingsIndexEntry("settings/backup_restore", "Backup & restore", IndexText.Plain("None"), IndexText.Res(R.string.import_online)),
    SettingsIndexEntry("settings/backup_restore", "Backup & restore", IndexText.Plain("None"), IndexText.Res(R.string.import_csv)),
    SettingsIndexEntry("settings/discord", "Discord", IndexText.Res(R.string.options), IndexText.Res(R.string.enable_discord_rpc)),
    SettingsIndexEntry("settings/discord", "Discord", IndexText.Res(R.string.options), IndexText.Res(R.string.discord_show_when_paused)),
    SettingsIndexEntry("settings/discord", "Discord", IndexText.Res(R.string.preview), IndexText.Res(R.string.discord_integration)),
    SettingsIndexEntry("settings/discord", "Discord", IndexText.Res(R.string.preview), IndexText.Plain("Edit \$title")),
    SettingsIndexEntry("settings/discord", "Discord", IndexText.Res(R.string.preview), IndexText.Res(R.string.preview)),
    SettingsIndexEntry("settings/integration", "Integrations", IndexText.Res(R.string.general), IndexText.Res(R.string.discord_integration)),
    SettingsIndexEntry("settings/integration", "Integrations", IndexText.Res(R.string.scrobbling), IndexText.Res(R.string.lastfm_integration)),
    SettingsIndexEntry("settings/integration", "Integrations", IndexText.Res(R.string.scrobbling), IndexText.Res(R.string.listenbrainz_scrobbling)),
    SettingsIndexEntry("settings/integration", "Integrations", IndexText.Res(R.string.scrobbling), IndexText.Res(R.string.integration)),
    SettingsIndexEntry("settings/lastfm", "Last.fm", IndexText.Plain("None"), IndexText.Res(R.string.login)),
    SettingsIndexEntry("settings/lastfm", "Last.fm", IndexText.Res(R.string.options), IndexText.Res(R.string.enable_scrobbling)),
    SettingsIndexEntry("settings/lastfm", "Last.fm", IndexText.Res(R.string.options), IndexText.Res(R.string.lastfm_now_playing)),
    SettingsIndexEntry("settings/lastfm", "Last.fm", IndexText.Res(R.string.scrobbling_configuration), IndexText.Res(R.string.scrobble_min_track_duration)),
    SettingsIndexEntry("settings/lastfm", "Last.fm", IndexText.Res(R.string.scrobbling_configuration), IndexText.Res(R.string.scrobble_delay_percent)),
    SettingsIndexEntry("settings/lastfm", "Last.fm", IndexText.Res(R.string.scrobbling_configuration), IndexText.Res(R.string.scrobble_delay_minutes)),
    SettingsIndexEntry("settings/lastfm", "Last.fm", IndexText.Res(R.string.scrobbling_configuration), IndexText.Res(R.string.lastfm_integration)),
    SettingsIndexEntry("settings/haptics", "Haptics", IndexText.Plain("None"), IndexText.Plain("Haptics")),
    SettingsIndexEntry("settings/android_auto", "Android Auto", IndexText.Plain("None"), IndexText.Res(R.string.android_auto)),
    SettingsIndexEntry("settings/android_auto", "Android Auto", IndexText.Plain("None"), IndexText.Res(R.string.android_auto_show_history)),
    SettingsIndexEntry("settings/android_auto", "Android Auto", IndexText.Plain("None"), IndexText.Res(R.string.android_auto_show_liked_songs)),
    SettingsIndexEntry("settings/android_auto", "Android Auto", IndexText.Plain("None"), IndexText.Res(R.string.android_auto_show_downloaded)),
    SettingsIndexEntry("settings/android_auto", "Android Auto", IndexText.Plain("None"), IndexText.Res(R.string.android_auto_show_youtube_playlists)),
    SettingsIndexEntry("settings/android_auto", "Android Auto", IndexText.Plain("None"), IndexText.Res(R.string.android_auto_song_sort)),
    SettingsIndexEntry("settings/android_auto", "Android Auto", IndexText.Plain("None"), IndexText.Res(R.string.android_auto_album_sort)),
    SettingsIndexEntry("settings/android_auto", "Android Auto", IndexText.Plain("None"), IndexText.Res(R.string.android_auto_artist_sort)),
    SettingsIndexEntry("settings/android_auto", "Android Auto", IndexText.Plain("None"), IndexText.Res(R.string.android_auto_item_limit)),
    SettingsIndexEntry("settings/appearance/always_on_display", "Always-on display", IndexText.Plain("None"), IndexText.Res(R.string.aod_screen_title)),
    SettingsIndexEntry("settings/music_together", "Music Together", IndexText.Plain("None"), IndexText.Res(R.string.together_display_name)),
    SettingsIndexEntry("settings/music_together", "Music Together", IndexText.Plain("None"), IndexText.Res(R.string.together_port)),
    SettingsIndexEntry("settings/music_together", "Music Together", IndexText.Plain("None"), IndexText.Res(R.string.join_session)),
    SettingsIndexEntry("settings/music_together", "Music Together", IndexText.Plain("None"), IndexText.Res(R.string.music_together)),
    SettingsIndexEntry("settings/music_together", "Music Together", IndexText.Plain("Where your friends are"), IndexText.Plain("Can add songs")),
    SettingsIndexEntry("settings/music_together", "Music Together", IndexText.Plain("Where your friends are"), IndexText.Plain("Can play, pause and skip")),
    SettingsIndexEntry("settings/music_together", "Music Together", IndexText.Plain("Where your friends are"), IndexText.Plain("Ask before letting someone in")),
    SettingsIndexEntry("settings/music_together", "Music Together", IndexText.Plain("Where your friends are"), IndexText.Plain("Relay server")),
    SettingsIndexEntry("settings/player/equalizer", "Equalizer", IndexText.Plain("None"), IndexText.Plain("Device effects")),
    SettingsIndexEntry("settings/player/equalizer", "Equalizer", IndexText.Plain("None"), IndexText.Res(R.string.system_audio_effects)),
    SettingsIndexEntry("settings/player/equalizer", "Equalizer", IndexText.Plain("None"), IndexText.Plain("Equalizer")),
    SettingsIndexEntry("settings/player", "Player & audio", IndexText.Plain("Sound"), IndexText.Plain("Crossfade")),
    SettingsIndexEntry("settings/player", "Player & audio", IndexText.Plain("Sound"), IndexText.Plain("Automix performance")),
    SettingsIndexEntry("settings/appearance/player_style", "Player style", null, IndexText.Plain("Player style")),
    SettingsIndexEntry("settings/content/lyrics_sources", "Lyrics sources", null, IndexText.Plain("Lyrics sources")),
    SettingsIndexEntry("settings/haptics", "Haptics", null, IndexText.Plain("Haptic intensity")),
    SettingsIndexEntry("settings/haptics", "Haptics", null, IndexText.Plain("How touches feel")),
)

/**
 * What people type for what the settings are called. Each word on the left also matches settings
 * containing any word on the right.
 */
val SettingsSynonyms: Map<String, List<String>> = mapOf(
    "font" to listOf("style", "typeface", "lettering"),
    "fonts" to listOf("style", "typeface"),
    "typeface" to listOf("style", "font"),
    "lettering" to listOf("style", "font"),
    "typography" to listOf("style", "font"),
    "singer" to listOf("artist"),
    "band" to listOf("artist"),
    "lockscreen" to listOf("lock", "screen"),
    "keyguard" to listOf("lock", "screen"),
    "dark" to listOf("theme", "black", "night"),
    "night" to listOf("dark", "theme"),
    "vibration" to listOf("haptic", "haptics"),
    "vibrate" to listOf("haptic", "haptics"),
    "buzz" to listOf("haptic"),
    "eq" to listOf("equalizer", "equaliser"),
    "equaliser" to listOf("equalizer"),
    "bass" to listOf("equalizer", "tone"),
    "treble" to listOf("equalizer", "tone"),
    "loud" to listOf("normalization", "volume"),
    "volume" to listOf("normalization", "loudness"),
    "fade" to listOf("crossfade", "automix"),
    "dj" to listOf("automix", "crossfade"),
    "mix" to listOf("automix", "crossfade"),
    "transition" to listOf("automix", "crossfade", "gapless"),
    "gapless" to listOf("crossfade", "automix"),
    "3d" to listOf("spatial"),
    "surround" to listOf("spatial"),
    "atmos" to listOf("spatial"),
    "quality" to listOf("audio", "bitrate", "codec"),
    "hifi" to listOf("quality", "lossless", "output"),
    "lossless" to listOf("quality", "output", "flac"),
    "dac" to listOf("usb", "output"),
    "karaoke" to listOf("lyrics"),
    "words" to listOf("lyrics"),
    "text" to listOf("lyrics", "font"),
    "font" to listOf("text", "typeface"),
    "size" to listOf("scale", "font"),
    "cache" to listOf("storage"),
    "space" to listOf("storage", "cache"),
    "offline" to listOf("download", "cache"),
    "history" to listOf("privacy", "listen"),
    "incognito" to listOf("privacy", "pause"),
    "scrobble" to listOf("last.fm", "lastfm"),
    "color" to listOf("colour", "palette", "theme"),
    "colour" to listOf("color", "palette", "theme"),
    "icon" to listOf("app icon"),
    "lockscreen" to listOf("always on display", "aod"),
    "car" to listOf("android auto"),
    "language" to listOf("content", "region"),
    "sleep" to listOf("timer"),
    "skip" to listOf("silence"),
    "player" to listOf("player style", "now playing"),
    "style" to listOf("player style", "design"),
    "look" to listOf("appearance", "theme", "player style"),
    "dock" to listOf("navigation", "tab bar", "nav bar"),
    "navbar" to listOf("dock", "navigation"),
    "nav" to listOf("dock", "navigation"),
    "navigation" to listOf("dock", "nav bar"),
    "tabbar" to listOf("dock", "tab bar"),
    "tab" to listOf("dock", "tabs"),
    "tabs" to listOf("dock", "tab bar"),
    "bottom" to listOf("dock", "bottom bar"),
    "bar" to listOf("dock", "nav bar"),
    "menu" to listOf("dock", "navigation"),
    "jelly" to listOf("dock", "jelly"),
    "pill" to listOf("dock", "capsule"),
)
